class Leg::Commands::Clean < Leg::Commands::BaseCommand
  def self.name
    "clean"
  end

  def self.summary
    "Delete files generated by the build command"
  end

  def run
    needs! :config
    needs! :config_clean

    select_step(current_or_latest_step) do
      shell_command(@config[:clean])
    end
  end
end

